;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        comment-line
        counsel-M-x
        forward-sexp
        haskell-indentation-common-electric-command
        indent-for-tab-command
        init-delete-excess-whitespace
        init-sp-kill-region-or-backward-word
        kill-sexp
        mark-sexp
        markdown-outdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-slurp-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-splice-sexp
        sp-up-sexp
        string-inflection-lower-camelcase
        transpose-sexps
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        dap-tooltip-mouse-motion
        end-of-defun
        handle-switch-frame
        init-multiple-cursors-edit
        ivy-switch-buffer
        lsp-ui-doc--handle-mouse-movement
        mc/mark-next-lines
        mc/mark-previous-lines
        mc/toggle-cursor-on-click
        mouse-start-secondary
        ))
