;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haskell-indentation-common-electric-command
        init-sp-kill-region-or-backward-word
        kill-sexp
        mark-sexp
        outshine-self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-word
        sp-splice-sexp
        transpose-sexps
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ))
