;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        counsel-M-x
        forward-sexp
        haskell-indentation-common-electric-command
        hydra--negative-argument
        init-delete-excess-whitespace
        init-sp-kill-region-or-backward-word
        kill-sexp
        mark-sexp
        markdown-outdent-or-delete
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-splice-sexp
        sp-up-sexp
        string-inflection-lower-camelcase
        transpose-sexps
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        init-multiple-cursors-edit
        mc/mark-next-lines
        mc/mark-previous-lines
        ))
